services:
  web:
    build: .
    container_name: php_app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: furniturevault
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    depends_on:
      - db

  backup:
    image: mysql:5.7
    container_name: mysql_backup
    volumes:
      - ./backup:/backup
    environment:
      - MYSQL_DATABASE=furniturevault
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    entrypoint: ["/bin/sh", "-c", "while true; do mysqldump -h db -u root furniturevault > /backup/db_backup_$(date +%F_%T).sql; sleep 86400; done"]
    depends_on:
      - db
      
volumes:
  db_data:
